#! /bin/bash
#unset CPATH
#unset C_INCLUDE_PATH
#unset CPLUS_INCLUDE_PATH
#unset OBJC_INCLUDE_PATH
#unset LIBS
#unset DYLD_FALLBACK_LIBRARY_PATH
#unset DYLD_FALLBACK_FRAMEWORK_PATH

#export SDKVER="4.3"
export DEVROOT="/Developer/Platforms/iPhoneOS.platform/Developer"
export SDKROOT="$DEVROOT/SDKs/iPhoneOS$SDKVER.sdk"
export MAINFOLDER=`pwd`
cd build >/dev/null 2>&1 && cmake .. -DCMAKE_TOOLCHAIN_FILE="$MAINFOLDER/script/CMake/toolchain/iphone.toolchain" -DCMAKE_INSTALL_PREFIX="/opt/iphone-$SDKVER" "$@"

